extends: htmlacademy/es6
env:
  es6: true,
  jquery: true
  browser: true,
globals:
  window: true
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: 0
  no-param-reassign: 0
  quotes: [2, "single", { "avoidEscape": true }]

# root: true

# parserOptions:
#   ecmaVersion: 6
#   sourceType: "module"

# env:
#   browser: true
#   es6: true

# extends:
#   "htmlacademy/es6"
